---
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
  codescene-ci-cd: empear/codescene-ci-cd@1.0.0

executors:
  py38:
    docker:
      - image: circleci/python:3.8
    environment:
      pyversion: 3-8
  py37:
    docker:
      - image: circleci/python:3.7
    environment:
      pyversion: 3-7
  py36:
    docker:
      - image: circleci/python:3.6
    environment:
      pyversion: 3-6
  py35:
    docker:
      - image: circleci/python:3.5
    environment:
      pyversion: 3-5

jobtemplate: &jobtemplate
    description: Run the test suite with {{ .Environment.pyversion }}
    steps:
      - checkout
      - restore_cache:
          key: venv-{{ checksum "setup.cfg" }}-v1
      - run:
          name: setup environment
          command: |
            if [ -d ~/.venv ]
            then
                echo "Virtual environment restored from cache"
            else
                python --version
                python -m venv ~/.venv
                . ~/.venv/bin/activate
                pip install -U -e .[dev]
            fi

      - save_cache:
          key: venv-{{ checksum "setup.cfg" }}-{{ .Environment.pyversion }}-v1
          paths:
            - ~/.venv

      - run:
          name: Run tests
          command: |
            . ~/.venv/bin/activate
            pytest --cov-report=xml --junitxml=coverage/junit.xml

      - store_artifacts:
          path: coverage
          destination: /

      - store_test_results:
          path: coverage

      - codecov/upload:
          file: coverage/coverage.xml

    working_directory: ~/docker-fixtures

jobs:
  test38:
    executor: py38
    <<: *jobtemplate

  test37:
    executor: py37
    <<: *jobtemplate

  test36:
    executor: py36
    <<: *jobtemplate

  test35:
    executor: py35
    <<: *jobtemplate

  package:
    executor: py37
    steps:
      - checkout
      - run:
          name: "Build and Upload Package"
          command: |
            python --version
            python setup.py sdist bdist_wheel
            cat > ~/.pypirc \<<HERE
            [distutils]
            index-servers =
              pypi

            [pypi]
            repository=https://test.pypi.org/legacy/
            username = ${CANS_PYPI_CIRCLECI_USERNAME}
            password = ${CANS_PYPI_CIRCLECI_PASSWORD}
            HERE
            twine upload -r pypi dist/*.whl
            rm ~/.pypirc
    working_directory: ~/docker-fixtures


workflows:
  version: 2
  test-and-package:
    jobs:
    - test35:
        name: "test3.5"
        context: py35

    - test36:
        name: "test3.6"
        context: py36

    - test37:
        name: "test3.7"
        context: py37

    - test38:
        name: "test3.8"
        context: py38

    - package:
        requires:
          - "test3.5"
          - "test3.6"
          - "test3.7"
          - "test3.8"
        filters:
          branches:
            ignore:
              - /.*/
          tags:
            only:
              - /v[0-9]+\.[0-9]+\.[0-9]+/
        context: py-package


# vim: et:sw=2:syntax=2:ts=2:
